In [171]:
import numpy as np
import sklearn as sk
from sklearn.model_selection import train_test_split

TO DO: import load_wine from sklearn.datasets
 Then, create an instance __dataset__ by calling load_wine()

In [172]:
from sklearn.datasets import load_wine
dataset = load_wine()

TO DO: Display dataset.keys() and the elements of dataset.

In [173]:
print(dataset.keys())

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])


In [174]:
print(dataset.DESCR)

.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178 (50 in each of three classes)
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- Alcohol
 		- Malic acid
 		- Ash
		- Alcalinity of ash  
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wines
 		- Proline

    - class:
            - class_0
            - class_1
            - class_2
		
    :Summary Statistics:
    
    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    ============================= ==== ===== ======= =====
    Alcohol:                      11.0  14.8    13.0   0.8
    Malic Acid:                   0.74  5.80    2.34  1.12
    Ash:                          1.36  3.23    2.36  0.27
    Alcalinity of Ash:            1

In [175]:
print(dataset.feature_names)

['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']


In [176]:
print(dataset.data)

[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]


In [177]:
print(dataset.target_names)

['class_0' 'class_1' 'class_2']


In [178]:
print(dataset.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


TO DO: Split dataset into train and test sets, and print the shape of X_train, y_train, X_test and y_test

In [179]:
X = dataset.data
y = dataset.target
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state=0)
print("X_train.shape = ", X_train.shape)
print("y_train.shape = ", y_train.shape)
print("X_test.shape = ", X_test.shape)
print("y_test.shape = ", y_test.shape)

X_train.shape =  (133, 13)
y_train.shape =  (133,)
X_test.shape =  (45, 13)
y_test.shape =  (45,)


TO DO: Build a classifier for the wine dataset using LogisicRegression, and print the accuracy on the training and test data.


In [180]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression().fit(X_train,y_train)
print("train score = ", lr.score(X_train, y_train))
print("test score = ", lr.score(X_test, y_test))

train score =  0.9924812030075187
test score =  0.9333333333333333


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


TO DO: Save the weight matrix and bias vector of the LogisticRegression instance as W_lr and b_lr. Then, print them.

In [181]:
W_lr = lr.coef_
b_lr = lr.intercept_
print(W_lr)
print(b_lr)

[[-1.32186429e-01  3.23965050e-01  1.84092284e-01 -2.58932260e-01
  -3.55944236e-02  2.38697315e-01  5.82114322e-01 -2.22946486e-02
   9.92276027e-02  1.09948852e-01 -1.73973402e-02  4.10341111e-01
   8.36031752e-03]
 [ 5.99095455e-01 -7.17070268e-01 -2.00230225e-01  2.11071050e-01
  -1.04352065e-02  2.06746427e-01  3.95799510e-01  1.36191938e-02
   3.85959371e-01 -1.24982865e+00  2.65765529e-01  4.38399876e-01
  -8.01466640e-03]
 [-4.66909026e-01  3.93105218e-01  1.61379407e-02  4.78612099e-02
   4.60296301e-02 -4.45443742e-01 -9.77913832e-01  8.67545481e-03
  -4.85186974e-01  1.13987979e+00 -2.48368189e-01 -8.48740987e-01
  -3.45651121e-04]]
[-0.04937168  0.10908187 -0.05971019]


TO DO: Build a classifier for the wine dataset using LinearSVC, and print the accuracy on the training and test data.

In [182]:
from sklearn.svm import LinearSVC

linearSVC = LinearSVC().fit(X_train,y_train)
print("train score = ", linearSVC.score(X_train, y_train))
print("test score = ", linearSVC.score(X_test, y_test))

train score =  0.7894736842105263
test score =  0.7111111111111111


/usr/local/lib/python3.6/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


TO DO: Save the weight matrix and bias vector of the LinearSVC instance as W_svc and b_svc. Then, print them.

In [183]:
W_svc = linearSVC.coef_
print(W_svc)
b_svc = linearSVC.intercept_
print(b_svc)

[[-2.78880164e-02 -2.15889791e-03 -1.20357533e-03 -1.04462948e-01
  -8.10223312e-03  9.95959148e-03  3.05490489e-02 -3.98453276e-03
   7.88365556e-03 -1.94485514e-02 -8.41591116e-04  1.69149177e-02
   3.30913576e-03]
 [ 4.62612737e-02 -7.90959000e-02 -6.02056555e-03  3.39273900e-02
   6.08386039e-03  4.30510291e-02  7.52166818e-02  1.20786439e-04
   4.47427597e-02 -1.96534852e-01  3.17070009e-02  8.68700188e-02
  -2.23966042e-03]
 [-4.61736400e-02  8.14867652e-02  1.06110028e-03  8.31857839e-03
  -1.92924949e-03 -6.18868644e-02 -1.25406554e-01  2.61791431e-03
  -5.55600277e-02  2.16024545e-01 -3.27743687e-02 -1.16070991e-01
   9.84424408e-04]]
[-0.00401683  0.00918276 -0.00681667]


TO DO: Define a class __SimpleLinearClassifier__ composed of the following functions:

* __\_\_init\_\___(self, weight, bias) - takes a weight matrix and a bias vector as input and stores them in instance variables

* __predict(self, X)__ - takes an array of rank 2 as input, and returns the classification results as an array of rank 1

* __probability(self, X)__ - takes an array of rank 2 as input and returns the probabilities that each sample belongs to each class as an array of rank 2. (You need to implement the softmax function to convert logits into probabilities.)

* __score(self, X, y)__ - takes an input data (rank 2) and a target vector (rank 1) as input, and returns the accuracy as a scalar value.


The __SimpleLinearClassifier__ should work as the following examples.

In [184]:
# Define SimpleLienarClassfier here.
def softmax(a) :
  exp_a = np.exp(a)
  sum_exp_a = np.sum(exp_a, axis = 1)
  sum_exp_a = np.expand_dims(sum_exp_a, axis=1)
  y = exp_a / sum_exp_a
  return y

class SimpleLienarClassfier:
  def __init__(self, weight, bias):
    self.w = weight
    self.b = bias
  
  def probability(self, X):
    temp_X = X.dot(self.w.T) + np.expand_dims(self.b, axis=0)
    return softmax(temp_X)

  def predict(self, X):
    temp_prob = self.probability(X)
    return np.argmax(temp_prob, axis=1)
  
  def score(self, X, y):
    a = self.predict(X)
    is_same = a == y
    c = a[is_same]
    return c.shape[0]/a.shape[0]

TO DO: Create a SimpleLinearClassfier instance simple_lr using W_lr and b_lr. Then, print the accuracy on the training and test data.<br>
(The accuracies should be the same as those of the LogisticRegression instance.)

In [185]:
simple_lr = SimpleLienarClassfier(W_lr, b_lr)
print(simple_lr.score(X_train,y_train))
print(simple_lr.score(X_test,y_test))

0.9924812030075187
0.9333333333333333


TO DO: Display the results of simple_lr.predict(X_test) along with y_test.

In [186]:
y_hat = simple_lr.predict(X_test)
print("y_hat = " , y_hat)
print("y_test = " , y_test)

y_hat =  [0 2 1 0 1 1 0 2 1 1 2 2 0 1 2 1 0 0 2 0 1 0 1 1 1 1 1 1 1 2 0 0 1 0 0 0 2
 1 1 2 1 0 1 1 1]
y_test =  [0 2 1 0 1 1 0 2 1 1 2 2 0 1 2 1 0 0 1 0 1 0 0 1 1 1 1 1 1 2 0 0 1 0 0 0 2
 1 1 2 0 0 1 1 1]


TO DO: Display the result of simple_lr.probability(X_test).
Then, check whether the sum of each row makes one.

In [187]:
print("prob = ",simple_lr.probability(X_test))
print(simple_lr.probability(X_test).sum(axis=1))

prob =  [[9.91523974e-01 1.06809396e-03 7.40793157e-03]
 [3.77327532e-06 1.30747729e-07 9.99996096e-01]
 [3.44245206e-03 9.96346395e-01 2.11152743e-04]
 [9.84160185e-01 1.48380428e-03 1.43560112e-02]
 [3.47198262e-03 9.96246866e-01 2.81151540e-04]
 [3.24070085e-03 9.92522269e-01 4.23702975e-03]
 [9.98974254e-01 8.79461736e-05 9.37799443e-04]
 [9.33756528e-04 9.70685064e-05 9.98969175e-01]
 [7.45239054e-03 9.91861675e-01 6.85934882e-04]
 [1.77271256e-03 9.97704602e-01 5.22685383e-04]
 [8.96380394e-02 1.14086635e-02 8.98953297e-01]
 [2.34976560e-03 2.79276387e-02 9.69722596e-01]
 [9.99918361e-01 3.14178153e-07 8.13251425e-05]
 [1.98520006e-01 8.00879300e-01 6.00693636e-04]
 [3.52047348e-04 1.71638882e-05 9.99630789e-01]
 [2.14401123e-05 9.99974013e-01 4.54707456e-06]
 [9.88633382e-01 7.01422817e-04 1.06651955e-02]
 [9.99961126e-01 9.20343542e-10 3.88732006e-05]
 [8.16704638e-03 1.12844947e-01 8.78988007e-01]
 [9.99869347e-01 5.27342750e-05 7.79184901e-05]
 [1.18290976e-01 8.81018904e-01 

TO DO: Print the accuracy on the training and test data.

In [188]:
print(simple_lr.score(X_train,y_train))
print(simple_lr.score(X_test,y_test))

0.9924812030075187
0.9333333333333333


TO DO: Create a SimpleLinearClassfier instance simple_svc using W_svc and b_svc. Then, print the accuracy on the training and test data.<br>
(The accuracies should be the same as those of the LinearSVC instance.)

In [189]:
simple_svc = SimpleLienarClassfier(W_svc, b_svc)
print(simple_svc.score(X_train,y_train))
print(simple_svc.score(X_test,y_test))

0.7894736842105263
0.7111111111111111


TO DO: Display the results of simple_svc.predict(X_test) along with y_test.

In [190]:
y_hat = simple_svc.predict(X_test)
print("y_hat = " , y_hat)
print("y_test = " , y_test)

y_hat =  [2 2 1 2 1 1 0 2 1 1 2 2 0 1 2 1 2 0 2 0 1 0 2 1 2 1 1 1 2 2 0 2 2 2 0 2 2
 1 1 2 2 2 1 1 1]
y_test =  [0 2 1 0 1 1 0 2 1 1 2 2 0 1 2 1 0 0 1 0 1 0 0 1 1 1 1 1 1 2 0 0 1 0 0 0 2
 1 1 2 0 0 1 1 1]


TO DO: Display the result of simple_svc.probability(X_test).
Then, check whether the sum of each row makes one.

In [191]:
print("prob = ",simple_svc.probability(X_test))
print("prob.sum(axis = 1) = " , simple_svc.probability(X_test).sum(axis=1))

prob =  [[0.41370298 0.08767762 0.4986194 ]
 [0.01733267 0.05090078 0.93176655]
 [0.07476692 0.6371551  0.28807798]
 [0.3336492  0.08161925 0.58473155]
 [0.04686202 0.67789903 0.27523895]
 [0.02292256 0.67194179 0.30513565]
 [0.55552907 0.04471566 0.39975527]
 [0.04273504 0.09745658 0.85980837]
 [0.11007208 0.52998937 0.35993855]
 [0.0995174  0.5751512  0.3253314 ]
 [0.13563177 0.11054997 0.75381826]
 [0.04672782 0.22289246 0.73037971]
 [0.67859697 0.01167457 0.30972845]
 [0.19621228 0.42460571 0.37918202]
 [0.04160377 0.0556456  0.90275062]
 [0.03421777 0.82683633 0.1389459 ]
 [0.43357948 0.07076529 0.49565522]
 [0.69509193 0.00277314 0.30213493]
 [0.07838876 0.3061594  0.61545184]
 [0.59754207 0.03555158 0.36690635]
 [0.17343156 0.44504491 0.38152354]
 [0.46771559 0.0849983  0.44728611]
 [0.13816181 0.39047496 0.47136323]
 [0.15974616 0.47493035 0.3653235 ]
 [0.20233319 0.30744139 0.49022542]
 [0.03292994 0.80524484 0.16182521]
 [0.04079738 0.71952771 0.2396749 ]
 [0.05727446 0.64825

TO DO: Print the accuracy on the training and test data.

In [192]:
print(simple_svc.score(X_train,y_train))
print(simple_svc.score(X_test,y_test))

0.7894736842105263
0.7111111111111111
